/**
 * attachments.js
 * Renders a small "supporting documents" widget: upload with a document
 * type (our WC, customer WC, 198 collection log, 184, other), list what's
 * attached, view or remove. Used wherever a record needs backup docs.
 * Files are stored as Blobs directly in IndexedDB — nothing leaves the browser.
 */
window.App = window.App || {};

App.Attachments = (function () {
  function typeOptions() {
    return App.Models.ATTACHMENT_DOCUMENT_TYPES
      .map((t) => `<option value="${t}">${t}</option>`)
      .join('');
  }

  function formatBytes(n) {
    if (!n) return '';
    if (n < 1024) return `${n} B`;
    if (n < 1024 * 1024) return `${(n / 1024).toFixed(0)} KB`;
    return `${(n / (1024 * 1024)).toFixed(1)} MB`;
  }

  /**
   * Renders into `container`. Requires the linked record to already exist
   * (linkedEntityId must be a real id — save the parent record first).
   */
  async function renderSection(container, { linkedEntityType, linkedEntityId }) {
    const wrap = document.createElement('div');
    wrap.className = 'panel';
    container.appendChild(wrap);

    async function refresh() {
      const all = await App.DB.getAllByIndex('attachments', 'linkedEntityId', linkedEntityId);
      const docs = all.filter((a) => a.linkedEntityType === linkedEntityType);

      wrap.innerHTML = `
        <h2>Supporting documents</h2>
        <p class="muted mt-0">Attach whatever you already have — your own Weight Certificate, the customer's copy, the 198 Collection Log, a 184, etc. Nothing here is generated by the app.</p>
        <form class="field-row" data-role="upload-form">
          <div class="field" style="flex:1;">
            <label>Document type</label>
            <select name="documentType">${typeOptions()}</select>
          </div>
          <div class="field" style="flex:2;">
            <label>File</label>
            <input type="file" name="file" required>
          </div>
        </form>
        <button type="button" class="primary" data-action="upload">Attach file</button>
        ${docs.length ? `
          <table style="margin-top:14px;">
            <thead><tr><th>Type</th><th>File</th><th>Size</th><th>Added</th><th></th></tr></thead>
            <tbody>
              ${docs.map((d) => `
                <tr>
                  <td><span class="badge">${d.documentType}</span></td>
                  <td>${d.filename}</td>
                  <td class="num">${formatBytes(d.blob && d.blob.size)}</td>
                  <td>${d.uploadedDate || ''}</td>
                  <td class="row">
                    <button type="button" data-view="${d.id}">View</button>
                    <button type="button" class="danger" data-remove="${d.id}">Remove</button>
                  </td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        ` : '<p class="muted" style="margin-top:14px;">No documents attached yet.</p>'}
      `;

      wrap.querySelector('[data-action="upload"]').addEventListener('click', async () => {
        const form = wrap.querySelector('[data-role="upload-form"]');
        const fd = new FormData(form);
        const file = fd.get('file');
        if (!file || !file.name) return;
        await App.DB.add('attachments', {
          linkedEntityType,
          linkedEntityId,
          documentType: fd.get('documentType'),
          filename: file.name,
          mimeType: file.type || 'application/octet-stream',
          blob: file,
          uploadedDate: new Date().toISOString().slice(0, 10),
          description: '',
        });
        await refresh();
      });

      wrap.querySelectorAll('[data-view]').forEach((btn) => {
        btn.addEventListener('click', async () => {
          const doc = await App.DB.get('attachments', Number(btn.dataset.view));
          if (!doc || !doc.blob) return;
          const url = URL.createObjectURL(doc.blob);
          window.open(url, '_blank');
        });
      });

      wrap.querySelectorAll('[data-remove]').forEach((btn) => {
        btn.addEventListener('click', async () => {
          if (!confirm('Remove this attachment?')) return;
          await App.DB.delete('attachments', Number(btn.dataset.remove));
          await refresh();
        });
      });
    }

    await refresh();
  }

  return { renderSection };
})();
