/* CalRecycle CBEP Claim Completeness Checklist (Apr 2026): each checkbox field → what it checks. Built from the form's
   own layout (the text beside each box), since the field numbering doesn't follow page order. */
window.App = window.App || {};
App.ChecklistMap = {
 "Lithiumion batteries": "cert:Lithium-ion Batteries",
 "Nickelmetal hydride batteries": "cert:Nickel-Metal Hydride Batteries",
 "Sealed leadacid batteries": "cert:Sealed Lead-Acid Batteries",
 "Nickelcadmium batteries": "cert:Nickel-Cadmium Batteries",
 "Other batteries": "cert:Other Batteries",
 "Plastic": "cert:Plastic",
 "Copper": "cert:Copper",
 "Noncopper metals": "cert:Non-Copper Metals",
 "Circuit boards": "cert:Circuit Boards",
 "Glass": "cert:Glass",
 "Fibers": "cert:Fibers",
 "Other specify": "cert:Other",
 "Recycler name": "cewis:name",
 "Federal employer identification number": "cewis:fein",
 "Recycler contact": "cewis:contact",
 "Reporting month": "cewis:month",
 "Claim activity period": "cewis:activity",
 "Cancellation method": "cewis:method",
 "Claimed pounds": "cewis:pounds",
 "Claimed  amount": "cewis:dollars",
 "Lithiumion batteries were shipped to a recycling facility": "bat:Lithium-ion Batteries:rec",
 "Accumulation start date": "bat:Lithium-ion Batteries:rec:acc",
 "Bill of lading": "bat:Lithium-ion Batteries:rec:bol",
 "Weighmaster certificate with no other residuals on it": "bat:Lithium-ion Batteries:rec:wc",
 "Receipt from the receiving destination The receipt from the receiving destination": "bat:Lithium-ion Batteries:rec:receipt",
 "Explanation of ultimate disposition If the ultimate disposition is different than the": "bat:Lithium-ion Batteries:rec:ultimate",
 "Lithiumion batteries were shipped to a hazardous waste landfill": "bat:Lithium-ion Batteries:land",
 "Accumulation start date_2": "bat:Lithium-ion Batteries:land:acc",
 "Hazardous waste manifest The manifest must include signatures from the generator": "bat:Lithium-ion Batteries:land:manifest",
 "Weighmaster certificate with no other residuals on it_2": "bat:Lithium-ion Batteries:land:wc",
 "Explanation of ultimate disposition If the ultimate disposition is different than the_2": "bat:Lithium-ion Batteries:land:ultimate",
 "Lithiumion batteries were stored": "bat:Lithium-ion Batteries:stored",
 "Accumulation start date_3": "bat:Lithium-ion Batteries:stored:acc",
 "Lithiumion batteries were not generated in this claim": "bat:Lithium-ion Batteries:none",
 "Nickel metal hydride batteries were shipped to a recycling facility": "bat:Nickel-Metal Hydride Batteries:rec",
 "Accumulation start date_4": "bat:Nickel-Metal Hydride Batteries:rec:acc",
 "Bill of lading_2": "bat:Nickel-Metal Hydride Batteries:rec:bol",
 "Weighmaster certificate with no other residuals on it_3": "bat:Nickel-Metal Hydride Batteries:rec:wc",
 "Receipt from the receiving destination The receipt from the receiving destination_2": "bat:Nickel-Metal Hydride Batteries:rec:receipt",
 "Explanation of ultimate disposition If the ultimate disposition is different than the_3": "bat:Nickel-Metal Hydride Batteries:rec:ultimate",
 "Nickelmetal hydride batteries were shipped to a hazardous waste landfill": "bat:Nickel-Metal Hydride Batteries:land",
 "Accumulation start date_5": "bat:Nickel-Metal Hydride Batteries:land:acc",
 "Hazardous waste manifest The manifest must include signatures from the": "bat:Nickel-Metal Hydride Batteries:land:manifest",
 "Weighmaster certificate with no other residuals on it_4": "bat:Nickel-Metal Hydride Batteries:land:wc",
 "Explanation of ultimate disposition If the ultimate disposition is different than the_4": "bat:Nickel-Metal Hydride Batteries:land:ultimate",
 "Nickelmetal hydride batteries were stored": "bat:Nickel-Metal Hydride Batteries:stored",
 "Accumulation start date_7": "bat:Nickel-Metal Hydride Batteries:stored:acc",
 "Nickelmetal hydride batteries were not generated in this claim": "bat:Nickel-Metal Hydride Batteries:none",
 "Sealed leadacid batteries were shipped to a recycling facility": "bat:Sealed Lead-Acid Batteries:rec",
 "Accumulation start date_8": "bat:Sealed Lead-Acid Batteries:rec:acc",
 "Bill of lading_3": "bat:Sealed Lead-Acid Batteries:rec:bol",
 "Weighmaster certificate with no other residuals on it_6": "bat:Sealed Lead-Acid Batteries:rec:wc",
 "Receipt from the receiving destination The receipt from the receiving destination_3": "bat:Sealed Lead-Acid Batteries:rec:receipt",
 "Explanation of ultimate disposition If the ultimate disposition is different than the_6": "bat:Sealed Lead-Acid Batteries:rec:ultimate",
 "Sealed leadacid batteries were shipped to a hazardous waste landfill": "bat:Sealed Lead-Acid Batteries:land",
 "Accumulation start date_6": "bat:Sealed Lead-Acid Batteries:land:acc",
 "Hazardous waste manifest The manifest must include signatures from the_2": "bat:Sealed Lead-Acid Batteries:land:manifest",
 "Weighmaster certificate with no other residuals on it_5": "bat:Sealed Lead-Acid Batteries:land:wc",
 "Explanation of ultimate disposition If the ultimate disposition is different than the_5": "bat:Sealed Lead-Acid Batteries:land:ultimate",
 "Sealed leadacid batteries were stored": "bat:Sealed Lead-Acid Batteries:stored",
 "Accumulation start date_9": "bat:Sealed Lead-Acid Batteries:stored:acc",
 "Sealed leadacid batteries were not generated in this claim": "bat:Sealed Lead-Acid Batteries:none",
 "Nickelcadmium batteries were shipped to a recycling facility": "bat:Nickel-Cadmium Batteries:rec",
 "Accumulation start date_10": "bat:Nickel-Cadmium Batteries:rec:acc",
 "Bill of lading_4": "bat:Nickel-Cadmium Batteries:rec:bol",
 "Weighmaster certificate with no other residuals on it_7": "bat:Nickel-Cadmium Batteries:rec:wc",
 "Receipt from the receiving destination The receipt from the receiving destination_4": "bat:Nickel-Cadmium Batteries:rec:receipt",
 "Explanation of ultimate disposition If the ultimate disposition is different than the_7": "bat:Nickel-Cadmium Batteries:rec:ultimate",
 "Nickelcadmium batteries were shipped to a hazardous waste landfill": "bat:Nickel-Cadmium Batteries:land",
 "Accumulation start date_14": "bat:Nickel-Cadmium Batteries:land:acc",
 "Hazardous waste manifest The manifest must include signatures from the_3": "bat:Nickel-Cadmium Batteries:land:manifest",
 "Weighmaster certificate with no other residuals on it_9": "bat:Nickel-Cadmium Batteries:land:wc",
 "Explanation of ultimate disposition If the ultimate disposition is different than the_9": "bat:Nickel-Cadmium Batteries:land:ultimate",
 "Nickelcadmium batteries were stored": "bat:Nickel-Cadmium Batteries:stored",
 "Accumulation start date_11": "bat:Nickel-Cadmium Batteries:stored:acc",
 "Nickelcadmium batteries were not generated in this claim": "bat:Nickel-Cadmium Batteries:none",
 "Other batteries were shipped to a recycling facility": "bat:Other Batteries:rec",
 "Accumulation start date_12": "bat:Other Batteries:rec:acc",
 "Bill of lading_5": "bat:Other Batteries:rec:bol",
 "Weighmaster certificate with no other residuals on it_8": "bat:Other Batteries:rec:wc",
 "Receipt from the receiving destination The receipt from the receiving destination_5": "bat:Other Batteries:rec:receipt",
 "Explanation of ultimate disposition If the ultimate disposition is different than the_8": "bat:Other Batteries:rec:ultimate",
 "Other batteries were shipped to a hazardous waste landfill": "bat:Other Batteries:land",
 "Accumulation start date_13": "bat:Other Batteries:land:acc",
 "Hazardous waste manifest The manifest must include signatures from the generator_2": "bat:Other Batteries:land:manifest",
 "Weighmaster certificate with no other residuals on it_10": "bat:Other Batteries:land:wc",
 "Explanation of ultimate disposition If the ultimate disposition is different than the_10": "bat:Other Batteries:land:ultimate",
 "Other batteries were stored": "bat:Other Batteries:stored",
 "Accumulation start date_15": "bat:Other Batteries:stored:acc",
 "Other batteries were not generated in this claim": "bat:Other Batteries:none",
 "A description of the material flow meaning the various brokers or facilities that some": "other:flow",
 "A weighmaster certificate": "other:wc",
 "If shipped to a hazardous waste landfill hazardous waste manifest The manifest": "other:manifest",
 "If shipped to a recycling facility a bill of lading": "other:bol",
 "The totals pounds of each residual shipped": "other:totals",
 "The shipping documents for each residual were summed The total claimed weigh for": "other:summed",
 "Date cancelled": "daily:date",
 "Pounds cancelled": "daily:pounds",
 "The method of cancellation selecting a cancellation method on 196 in CEWIS will meet": "daily:method",
 "The total lbs cancelledclaimed lbs": "daily:equal",
 "A transfer summary was provided": "tr:summary",
 "Transfer receipt": "tr:receipt",
 "Weighmaster certificate": "tr:wc",
 "Collection logs": "tr:logs",
 "Source Anonymous logs if applicable": "tr:sa",
 "Proof of Designation POD if applicable": "tr:pod",
 "The units and weight from every transfer receipt were added together The sums": "tr:added",
 "The total weight transferred and claimed weight cancelled If the claim does not include": "tr:equal"
};
